# Generated by Django 4.2.28 on 2026-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('e_wallet', 'E-Wallet'), ('cash', 'Cash'), ('qris', 'QRIS')], max_length=20),
        ),
    ]
