# Generated by Django 4.2.28 on 2026-02-14 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'db_table': 'ticket_types',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='check_non_negative_price'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='check_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(('sold__gte', 0)), name='check_non_negative_sold'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(('sold__lte', models.F('quantity'))), name='check_sold_not_exceed_quantity'),
        ),
    ]
